export const ATTENDANCE_TABLE_DATA = [
  {
    name: "Dina",
    position: "Team Lead - Design",
    location: "Remote",
    time: "10:24 AM",
    status: "On Time",
  },
  {
    name: "David",
    position: "Analyst",
    location: "Office",
    time: "09:15 AM",
    status: "On Time",
  },
  {
    name: "Alice",
    position: "Developer",
    location: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
  {
    name: "Charlie",
    position: "Manager",
    location: "Remote",
    time: "10:15 AM",
    status: "On Time",
  },
  {
    name: "Bob",
    position: "Designer",
    location: "Office",
    time: "09:00 AM",
    status: "Late",
  },
];

export const EMPLOYEE_TABLE_DATA = [
  {
    name: "Alice",
    id: "000666000",
    department: "Developement",
    designation: "UI/UX Designer",
    type: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
  {
    name: "Alice",
    id: "000666000",
    department: "Developement",
    designation: "UI/UX Designer",
    type: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
  {
    name: "Alice",
    id: "000666000",
    department: "Developement",
    designation: "UI/UX Designer",
    type: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
  {
    name: "Alice",
    id: "000666000",
    department: "Developement",
    designation: "UI/UX Designer",
    type: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
  {
    name: "Alice",
    id: "000666000",
    department: "Developement",
    designation: "UI/UX Designer",
    type: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
  {
    name: "Alice",
    id: "000666000",
    department: "Developement",
    designation: "UI/UX Designer",
    type: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
  {
    name: "Alice",
    id: "000666000",
    department: "Developement",
    designation: "UI/UX Designer",
    type: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
  {
    name: "Alice",
    id: "000666000",
    department: "Developement",
    designation: "UI/UX Designer",
    type: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
];
export const EMPLOYEE_TABLE_HEAD = [
  { heading: "Employee Name" },
  { heading: "Employee ID" },
  { heading: "Department" },
  { heading: "Designation" },
  { heading: "Type" },
  { heading: "Status" },
  { heading: "Action" },
];
export const PROFILE_ATTENDANCE_TABLE_HEAD = [
  { heading: "Date" },
  { heading: "Check In" },
  { heading: "Check Out" },
  { heading: "Break" },
  { heading: "Working Hours" },
  { heading: "Status" },
];
export const PROFILE_TABLE_ATTENDANCE_DATA = [
  {
    date: "2023-06-01",
    checkIn: "09:00 AM",
    checkOut: "05:00 PM",
    break: "1 hour",
    workingHours: "7 hours",
    status: "On Time",
  },
  {
    date: "2023-06-01",
    checkIn: "09:15 AM",
    checkOut: "05:15 PM",
    break: "1 hour",
    workingHours: "7 hours",
    status: "On Time",
  },
  {
    date: "2023-06-01",
    checkIn: "09:15 AM",
    checkOut: "05:15 PM",
    break: "1 hour",
    workingHours: "7 hours",
    status: "Late",
  },
  {
    date: "2023-06-01",
    checkIn: "09:15 AM",
    checkOut: "05:15 PM",
    break: "1 hour",
    workingHours: "7 hours",
    status: "Late",
  },
  {
    date: "2023-06-01",
    checkIn: "09:15 AM",
    checkOut: "05:15 PM",
    break: "1 hour",
    workingHours: "7 hours",
    status: "On Time",
  },
  {
    date: "2023-06-01",
    checkIn: "09:15 AM",
    checkOut: "05:15 PM",
    break: "1 hour",
    workingHours: "7 hours",
    status: "On Time",
  },
];

export const DEMO_DATA = {
  firstName: "Dina",
  lastName: "Convea",
  mobileNumber: "091391203123",
  emailAddress: "user@email.com",
  dateOfBirth: "July 20,1992",
  maritalStatus: "Tlaaq yafta",
  gender: "All Gender",
  nationality: "Chapri",
  address: "Post Office",
  city: "Tokyo",
  state: "Mosco",
  zipCode: "9687",
};
export const PROFILE_PERSONAL_HEADINGS = {
  "First Name": "firstName",
  "Last Name": "lastName",
  "Mobile Number": "mobileNumber",
  "Email Address": "emailAddress",
  "Date of Birth": "dateOfBirth",
  Address: "address",
  City: "city",
  Gender: "gender",
  "Marital Status": "maritalStatus",
  Nationality: "nationality",
  State: "state",
  "Zip Code": "zipCode",
};
export const PROFILE_PROJECT_TABLE_HEADINGS = [
  { heading: "Sr.No." },
  { heading: "Project Name" },
  { heading: "Start Date" },
  { heading: "End Date" },
  { heading: "Status" },
];
export const PROFILE_LEAVE_TABLE_HEADINGS = [
  { heading: "Date" },
  { heading: "Duration" },
  { heading: "Days" },
  { heading: "Reproting Manager" },
  { heading: "Status" },
];
export const PROFILE_PROJECT_TABLE_DATA = [
  {
    projectName: "Taskify",
    startDate: "April 12,2022",
    endDate: "July 12,2025",
    status: "Pending",
  },
  {
    projectName: "Trello",
    startDate: "April 12,2022",
    endDate: "July 12,2025",
    status: "Completed",
  },
];
export const PROFILE_LEAVE_TABLE_DATA = [
  {
    date: "June 2, 2025",
    duration: "July 05 - July 08",
    days: "12",
    reportingManager: "Sam Karan",
    status: "Pending",
  },
  {
    date: "June 2, 2025",
    duration: "July 05 - July 08",
    days: "12",
    reportingManager: "Sam Karan",
    status: "Approved",
  },
  {
    date: "May 21, 2025",
    duration: "July 05 - July 08",
    days: "2",
    reportingManager: "Sam Karan",
    status: "Reject",
  },
];
export const EMPLOYEE_ATTENDACE_TABLE_HEADS = [
  "Employee Name",
  "Designation",
  "Type",
  "Check In Time",
  "Status",
];
