export const ATTENDANCE_TABLE_DATA = [
  {
    name: "Dina",
    position: "Team Lead - Design",
    location: "Remote",
    time: "10:24 AM",
    status: "On Time",
  },
  {
    name: "David",
    position: "Analyst",
    location: "Office",
    time: "09:15 AM",
    status: "On Time",
  },
  {
    name: "Alice",
    position: "Developer",
    location: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
  {
    name: "Charlie",
    position: "Manager",
    location: "Remote",
    time: "10:15 AM",
    status: "On Time",
  },
  {
    name: "Bob",
    position: "Designer",
    location: "Office",
    time: "09:00 AM",
    status: "Late",
  },
];

export const EMPLOYEE_TABLE_DATA = [
  {
    name: "Alice",
    id: "000666000",
    department: "Developement",
    designation: "UI/UX Designer",
    type: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
  {
    name: "Alice",
    id: "000666000",
    department: "Developement",
    designation: "UI/UX Designer",
    type: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
  {
    name: "Alice",
    id: "000666000",
    department: "Developement",
    designation: "UI/UX Designer",
    type: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
  {
    name: "Alice",
    id: "000666000",
    department: "Developement",
    designation: "UI/UX Designer",
    type: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
  {
    name: "Alice",
    id: "000666000",
    department: "Developement",
    designation: "UI/UX Designer",
    type: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
  {
    name: "Alice",
    id: "000666000",
    department: "Developement",
    designation: "UI/UX Designer",
    type: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
  {
    name: "Alice",
    id: "000666000",
    department: "Developement",
    designation: "UI/UX Designer",
    type: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
  {
    name: "Alice",
    id: "000666000",
    department: "Developement",
    designation: "UI/UX Designer",
    type: "Remote",
    time: "08:30 AM",
    status: "Delayed",
  },
];
export const EMPLOYEE_TABLE_HEAD = [
  { heading: "Employee Name" },
  { heading: "Employee ID" },
  { heading: "Department" },
  { heading: "Designation" },
  { heading: "Type" },
  { heading: "Status" },
  { heading: "Action" },
];
