export const PROFILE_PERSONAL_INFO = [
  { key: "firstName", label: "First Name" },
  { key: "lastName", label: "Last Name" },
  { key: "mobileNumber", label: "Mobile Number" },
  { key: "emailAddress", label: "Email Address" },
  { key: "dateOfBirth", label: "Date of Birth" },
  { key: "maritalStatus", label: "Marital Status" },
  { key: "gender", label: "Gender" },
  { key: "nationality", label: "Nationality" },
  { key: "address", label: "Address" },
  { key: "city", label: "City" },
  { key: "state", label: "State" },
  { key: "zipCode", label: "Zip Code" },
];
export const PROFILE_PROFESSIONAL_INFO = [
  { key: "employeeId", label: "Employee ID" },
  { key: "userName", label: "User Name" },
  { key: "employmentType", label: "Employement Type" },
  { key: "email", label: "Email Address" },
  { key: "department", label: "Department" },
  { key: "designation", label: "Designation" },
  { key: "workingDays", label: "Working Days" },
  { key: "joiningDate", label: "Joining Date" },
  { key: "officeLocation", label: "Office Location" },
];
export const PROFILE_ACCOUNT_ACCESS = [
  { key: "email", label: "Email Address" },
  { key: "slackId", label: "Slack ID" },
  { key: "skypeId", label: "Skype ID" },
  { key: "githubId", label: "Github ID" },
];
export const EMPLOYEE_VALIDATION_FORM_ITEMS = [
  "firstName",
  "lastName",
  "mobileNumber",
  "emailAddress",
  "dateOfBirth",
  "gender",
  "maritalStatus",
  "nationality",
  "address",
  "city",
  "state",
  "zipCode",
  "employeeId",
  "userName",
  "employmentType",
  "department",
  "designation",
  "workingDays",
  "joiningDate",
  "officeLocation",
  "email",
  "slackId",
  "skypeId",
  "githubId",
];
