export const PROFILE_PERSONAL_INFO = [
  "First Name",
  "Last Name",
  "Mobile Number",
  "Email Address",
  "Date of Birth",
  "Marital Status",
  "Gender",
  "Nationality",
  "Address",
  "City",
  "State",
  "Zip Code",
];
export const PROFILE_PROFESSIONAL_INFO = [
  "Employee ID",
  "User Name",
  "Employee Type",
  "Email Address",
  "Department",
  "Designation",
  "Working Days",
  "Joining Date",
  "Office Location",
];
export const PROFILE_ACCOUNT_ACCESS = [
  "Email Address",
  "Slack ID",
  "Skype ID",
  "Github Id",
];
export const EMPLOYEE_VALIDATION_FORM_ITEMS = [
  "firstName",
  "lastName",
  "mobileNumber",
  "emailAddress",
  "dateOfBirth",
  "gender",
  "maritalStatus",
  "nationality",
  "address",
  "city",
  "state",
  "zipCode",
  "employeeId",
  "userName",
  "employmentType",
  "department",
  "designation",
  "workingDays",
  "joiningDate",
  "officeLocation",
  "email",
  "slackId",
  "skypeId",
  "githubId",
];
